### PR TITLE
Cloudstack agent running on docker

### PR DESCRIPTION
**Pull request by thebillkidy**

### CODE REVIEW

**Comment by terbolous** [comment]
Thanks for the pull request, testing now :-)

**Comment by thebillkidy** [comment]
Great, some bugs could still arise since tit is quite a complicated problem. The thing I also still have to try is to put the docker0 bridge as the default to use Private IP Address bridge.

It should be a parameter in:

```
execute_cmd "add traffictype traffictype=Guest physicalnetworkid=$phy_id"
```

I think it was something with kvm....=docker0 or something, but the problem was when I did that it wouldn't install, so now I manually move the vnets of the ssvm and cpvm to the docker0 bridge after creation (which is bad).

**Comment by thebillkidy** [comment]
I just removed the need for the vnet interfaces and moved the communication to the docker0 bridge, fixes some bugs for cloudstack on top of cloudstack

**Comment by terbolous** [comment]
Thanks for the update. I seem to be missing the part where the kvm host is assigned 10.30.28.4

**Comment by thebillkidy** [comment]
That is normal, I run it on a hypervisor and that machine has that ip allocated, I do not set it in the scripts. There are still some bugs that I am currently working on though

**Comment by terbolous** [comment]
Had a few hickups, mostly because my lab is running Ubuntu, but I see no problem with merging and fixing it

**Pull request merged**
